# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
 branches:
    include:
    - main
    - develop


stages:
- stage: Build
  jobs:
  - job: Build
    
    variables:
        buildConfiguration: 'Release'

    pool:
      vmImage: 'ubuntu-latest'
      
    steps:
    
    - script: dotnet build --configuration $(buildConfiguration)
      displayName: 'dotnet build $(buildConfiguration)'

    - task: DotNetCoreCLI@2
      inputs:
       command: 'publish'
       publishWebProjects: true

- stage: Deploy
  jobs:
  - job: Deploy
  
    pool:
       vmImage: 'ubuntu-latest'

    steps:
       - task: DownloadBuildArtifacts@0
         inputs:
             buildType: 'current'
             downloadType: 'single'
             artifactName: 'drop'
             downloadPath: '$(System.ArtifactsDirectory)'
       - task: AzureRmWebAppDeployment@4
         inputs:
             ConnectionType: 'AzureRM'
             azureSubscription: 'devspn'
             appType: 'webApp'
             WebAppName: 'sotj2'
             packageForLinux: '$(System.DefaultWorkingDirectory)/**/*.zip'

      
